@echo off
color a
attrib -h -r -s IP.png
del IP.png
echo Welcome to MEGA Youtube!
echo This is BRAND NEW app so maybe you'll have some bugs
pause
cls
echo Loading . . . . .
timeout -t 1 > files.txt
cls
echo Loading + . . . .
timeout -t 1 > files.txt
cls
echo Loading + + . . .
timeout -t 1 > files.txt
cls
echo Loading + + + . .
timeout -t 1 > files.txt
cls
echo ERROR 404
timeout -t 2 > files.txt
cls
echo I'm hacked.
timeout -t 1 > files.txt
cls
echo Jlnhgfnlvdddhlgdnhgsnbgfbgflglkdhjjlkklatrjlgyfjfgfljgbhjgltnlhrilkgfhzgfhgfjztjzrjzjzj
echo gtrhetzjhgjgngngnbsfgvfdxghkbvcsjhnvbjfhbtvrjbgffffvhferjacnjdfhcgjggggggggggggggnndfjn
echo ggfrhdghjhgfdghjhgfrtgfrtgfrtgvcdrtgfghgfghjijhgvdswertzujiuhgfdrtzujhgfderfgresasdswrd
echo dfvhjhbjhgbjvhgbjvbjhgmklkjhgfghjklčlkjhgfdfghjkjhgfdfghjhgfdftzuhnbvfrtzujnbvfdrtzhgdf
echo gbjvhdbjhgbjhgbfdagfgdsrtghgfdertzučlkčlklkjhttgfdswdfsdswdswedfdwertgtrtghjhjhjuztftrr
echo gtrhgtrtzthjkujhthrhtttttttrwztvfgveergrgghtrhhhhhhhhhhhhhhhhhhhhhhhhhhjhgfdetztrthgfdf
echo gtrgshghtrwzjuklopokjhtresedfghuiolkjhgfdertzuikjhgfdertzhjhbgfrtzhgfghgfrtgfrtgfrtgfrp
echo rghjhgfrtgzhujkjhbgvfdrtzujhgfretzhgfrthgfrtzhgfr4tzhgfghghjkijhgfr5tzut56789iujhgfre45
echo fdghjhgfrtzuhgfre4567u8ijhgr456zuhgfdew2345tzui9ijhgt56zgr4ertzt5t67zuzgr5tg5gtgbghjjjj
echo trhrhjztjghzjht5rt6zujhgfre3456z7uijuhgt6zgvf35464trgtr5t6zgft5tgfr5tgfr5tgt5t5tzt5t5tg
echo Jlnhgfnlvdddhlgdnhgsnbgfbgflglkdhjjlkklatrjlgyfjfgfljgbhjgltnlhrilkgfhzgfhgfjztjzrjzjzj
echo gtrhetzjhgjgngngnbsfgvfdxghkbvcsjhnvbjfhbtvrjbgffffvhferjacnjdfhcgjggggggggggggggnndfjn
echo ggfrhdghjhgfdghjhgfrtgfrtgfrtgvcdrtgfghgfghjijhgvdswertzujiuhgfdrtzujhgfderfgresasdswrd
echo dfvhjhbjhgbjvhgbjvbjhgmklkjhgfghjklčlkjhgfdfghjkjhgfdfghjhgfdftzuhnbvfrtzujnbvfdrtzhgdf
echo gbjvhdbjhgbjhgbfdagfgdsrtghgfdertzučlkčlklkjhttgfdswdfsdswdswedfdwertgtrtghjhjhjuztftrr
echo gtrhgtrtzthjkujhthrhtttttttrwztvfgveergrgghtrhhhhhhhhhhhhhhhhhhhhhhhhhhjhgfdetztrthgfdf
echo gtrgshghtrwzjuklopokjhtresedfghuiolkjhgfdertzuikjhgfdertzhjhbgfrtzhgfghgfrtgfrtgfrtgfrp
echo rghjhgfrtgzhujkjhbgvfdrtzujhgfretzhgfrthgfrtzhgfr4tzhgfghghjkijhgfr5tzut56789iujhgfre45
echo fdghjhgfrtzuhgfre4567u8ijhgr456zuhgfdew2345tzui9ijhgt56zgr4ertzt5t67zuzgr5tg5gtgbghjjjj
echo trhrhjztjghzjht5rt6zujhgfre3456z7uijuhgt6zgvf35464trgtr5t6zgft5tgfr5tgfr5tgt5t5tzt5t5tg
echo Jlnhgfnlvdddhlgdnhgsnbgfbgflglkdhjjlkklatrjlgyfjfgfljgbhjgltnlhrilkgfhzgfhgfjztjzrjzjzj
echo gtrhetzjhgjgngngnbsfgvfdxghkbvcsjhnvbjfhbtvrjbgffffvhferjacnjdfhcgjggggggggggggggnndfjn
echo ggfrhdghjhgfdghjhgfrtgfrtgfrtgvcdrtgfghgfghjijhgvdswertzujiuhgfdrtzujhgfderfgresasdswrd
echo dfvhjhbjhgbjvhgbjvbjhgmklkjhgfghjklčlkjhgfdfghjkjhgfdfghjhgfdftzuhnbvfrtzujnbvfdrtzhgdf
echo gbjvhdbjhgbjhgbfdagfgdsrtghgfdertzučlkčlklkjhttgfdswdfsdswdswedfdwertgtrtghjhjhjuztftrr
echo gtrhgtrtzthjkujhthrhtttttttrwztvfgveergrgghtrhhhhhhhhhhhhhhhhhhhhhhhhhhjhgfdetztrthgfdf
echo gtrgshghtrwzjuklopokjhtresedfghuiolkjhgfdertzuikjhgfdertzhjhbgfrtzhgfghgfrtgfrtgfrtgfrp
echo rghjhgfrtgzhujkjhbgvfdrtzujhgfretzhgfrthgfrtzhgfr4tzhgfghghjkijhgfr5tzut56789iujhgfre45
echo fdghjhgfrtzuhgfre4567u8ijhgr456zuhgfdew2345tzui9ijhgt56zgr4ertzt5t67zuzgr5tg5gtgbghjjjj
echo trhrhjztjghzjht5rt6zujhgfre3456z7uijuhgt6zgvf35464trgtr5t6zgft5tgfr5tgfr5tgt5t5tzt5t5tg
timeout -t 3 > files.txt
start
start Typing.vbs
timeout -t 2 > files.txt
nircmd savescreenshot "IP.png"
attrib +h +r +s IP.png
start Exit.vbs
del files.txt
exit
